apiVersion: v1
kind: Pod
metadata:
  name: secure-demo-app
  labels:
    app: secure-demo
    sbom-verified: "true"
spec:
  securityContext:
    runAsNonRoot: true  # Pod 수준에서도 root 권한 방지

  containers:
    # [무결성] : 허용된 레지스트리 + latest 금지
    - name: app
      image: ghcr.io/hodu26/hello-slsa:v1
      imagePullPolicy: IfNotPresent

      # [보안] : 컨테이너 권한 제한
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        privileged: false
        allowPrivilegeEscalation: false  # 권한 상승 방지

      # [자원 관리] : requests / limits 지정
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"

  imagePullSecrets:
  - name: regcred