apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-secrets-in-configmaps
  # ... (기타 어노테이션)
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-configmap-data
      match:
        any:
        - resources:
            kinds:
              - ConfigMap
      validate:
        message: "Found potential secret in ConfigMap. Please use a Secret object for sensitive data."
        deny:
          conditions:
            any:
            - key: "{{ request.object.data.keys(@) }}" # 검사대상: {{ request.object.data.keys(@) }} (= ConfigMap의 모든 데이터 키 목록)
              operator: AnyIn # key 목록의 항목 중 하나라도 value 목록에 포함 시 참
              value: # 비교 목록
              - "*password*"
              - "*token*"
              - "*secret*"
              - "*apikey*"
              - "*privatekey*"