apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-networkpolicy
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: require-network-policy
    match:
      any:
      - resources:
          kinds:
          - Pod
    exclude: # 특정 네임스페이스는 정책 검사에서 제외
      any:
      - resources:
          namespaces:
          - kube-system
          - kube-public
          - kube-node-lease
          - kyverno # Kyverno 자체는 네트워크 정책 없이도 동작해야 합니다.
    context: # 정책 결정을 위해 외부 데이터(API 서버 정보)를 조회
    - name: networkpolicies # 가져온 데이터를 'networkpolicies' 변수에 저장
      apiCall: # API 요청경로 & 응답 내 추출값 지정
        urlPath: "/apis/networking.k8s.io/v1/namespaces/{{request.namespace}}/networkpolicies" # {{request.namespace}}: 현재 요청이 들어온 네임스페이스를 동적으로 참조하여 치환
        jmesPath: "items[]" # API 응답(JSON)에서 'items' 배열만 추출
    validate:
      message: "A NetworkPolicy is required in this namespace. Please create one to control traffic."
      deny:
        conditions:
          all:
            - key: "{{ networkpolicies }}" # context에서 가져온 networkpolicies 변수
              operator: Equals # 값이 같은지 비교
              value: [] # 빈 배열([]) = NetworkPolicy가 하나도 없음 => "거부"